name: generate-snake-game

on:
  schedule:
    - cron: "0 0 * * *" # daily at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: MR-VL
          outputs: |
            dist/github-contribution-grid-snake-custom.svg?color_snake=#00FF00&color_dots=#4B0082,#551A8B,#6A0DAD,#7B1FA2,#9C27B0

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
